name: flutter_lorem
description: Generates random sentences and paragraphs (similar to "lorem ipsum" generators).
version: 2.0.0
homepage: https://github.com/dmjones/flutter_lorem

environment:
  sdk: '>=2.12.0-259 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
